-- auto-generated definition
create table jowto_data_count
(
    id                                int auto_increment comment '主键ID'
        primary key,
    jowto_count                       varchar(255)                       null comment '需要安装Jowto设备总量',
    jowto_online_count                varchar(255)                       null comment '需要安装Jowto设备在线数量',
    jowto_online_rate                 varchar(255)                       null comment '需要安装Jowto设备在线比例',
    jowto_offline_count               varchar(255)                       null comment '需要安装Jowto设备离线数量',
    jowto_offline_rate                varchar(255)                       null comment '需要安装Jowto设备离线比例',
    jowto_installed_count             varchar(255)                       null comment '需要安装Jowto设备已安装数量',
    jowto_installed_rate              varchar(255)                       null comment '需要安装Jowto设备已安装比例',
    jowto_uninstalled_count           varchar(255)                       null comment '需要安装Jowto设备未安装数量',
    jowto_uninstalled_rate            varchar(255)                       null comment '需要安装Jowto设备未安装比例',
    business_system_count             varchar(255)                       null comment '重点业务系统总量',
    business_system_online_count      varchar(255)                       null comment '重点业务系统在线数量',
    business_system_online_rate       varchar(255)                       null comment '重点业务系统在线比例',
    business_system_offline_count     varchar(255)                       null comment '重点业务系统离线数量',
    business_system_offline_rate      varchar(255)                       null comment '重点业务系统离线比例',
    business_system_installed_count   varchar(255)                       null comment '重点业务系统已安装jowto数量',
    business_system_installed_rate    varchar(255)                       null comment '重点业务系统已安装jowto比例',
    business_system_uninstalled_count varchar(255)                       null comment '重点业务系统未安装jowto数量',
    business_system_uninstalled_rate  varchar(255)                       null comment '重点业务系统未安装jowto比例',
    internet_expose_count             varchar(255)                       null comment '互联网暴露设备总量',
    internet_expose_online_count      varchar(255)                       null comment '互联网暴露设备在线数量',
    internet_expose_online_rate       varchar(255)                       null comment '互联网暴露设备在线比例',
    internet_expose_offline_count     varchar(255)                       null comment '互联网暴露设备离线数量',
    internet_expose_offline_rate      varchar(255)                       null comment '互联网暴露设备离线比例',
    internet_expose_installed_count   varchar(255)                       null comment '互联网暴露设备已安装jowto数量',
    internet_expose_installed_rate    varchar(255)                       null comment '互联网暴露设备已安装jowto比例',
    internet_expose_uninstalled_count varchar(255)                       null comment '互联网暴露设备未安装jowto数量',
    internet_expose_uninstalled_rate  varchar(255)                       null comment '互联网暴露设备未安装jowto比例',
    s1_count                          varchar(255)                       null comment 'S1安全域需要安装jowto设备总量',
    s1_online_count                   varchar(255)                       null comment 'S1安全域需要安装jowto设备在线数量',
    s1_online_rate                    varchar(255)                       null comment 'S1安全域需要安装jowto设备在线比例',
    s1_offline_count                  varchar(255)                       null comment 'S1安全域需要安装jowto设备离线数量',
    s1_offline_rate                   varchar(255)                       null comment 'S1安全域需要安装jowto设备离线比例',
    s1_installed_count                varchar(255)                       null comment 'S1安全域需要安装jowto设备已安装数量',
    s1_installed_rate                 varchar(255)                       null comment 'S1安全域需要安装jowto设备已安装比例',
    s1_uninstalled_count              varchar(255)                       null comment 'S1安全域需要安装jowto设备未安装数量',
    s1_uninstalled_rate               varchar(255)                       null comment 'S1安全域需要安装jowto设备未安装比例',
    s3_count                          varchar(255)                       null comment 'S3安全域需要安装jowto设备总量',
    s3_online_count                   varchar(255)                       null comment 'S3安全域需要安装jowto设备在线数量',
    s3_online_rate                    varchar(255)                       null comment 'S3安全域需要安装jowto设备在线比例',
    s3_offline_count                  varchar(255)                       null comment 'S3安全域需要安装jowto设备离线数量',
    s3_offline_rate                   varchar(255)                       null comment 'S3安全域需要安装jowto设备离线比例',
    s3_installed_count                varchar(255)                       null comment 'S3安全域需要安装jowto设备已安装数量',
    s3_installed_rate                 varchar(255)                       null comment 'S3安全域需要安装jowto设备已安装比例',
    s3_uninstalled_count              varchar(255)                       null comment 'S3安全域需要安装jowto设备未安装数量',
    s3_uninstalled_rate               varchar(255)                       null comment 'S3安全域需要安装jowto设备未安装比例',
    note                              varchar(500)                       null comment '备注',
    createTime                        datetime default CURRENT_TIMESTAMP null comment '创建时间',
    updateTime                        datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间'
)
    comment 'Jowto数据统计表';

